// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SudoBox.UnifiedModule.Infrastructure.DbContext;

#nullable disable

namespace SudoBox.UnifiedModule.Infrastructure.Migrations
{
    [DbContext(typeof(UnifiedDbContext))]
    [Migration("20250928195441_AddedNotBeforeNotAfterToCSR")]
    partial class AddedNotBeforeNotAfterToCSR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("unified")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertificateUser", b =>
                {
                    b.Property<string>("MyCertificatesSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("my_certificates_serial_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MyCertificatesSerialNumber", "UserId")
                        .HasName("pk_certificate_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_certificate_user_user_id");

                    b.ToTable("certificate_user", "unified");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.CertificateRequests.CertificateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EncodedCSR")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("encoded_csr");

                    b.Property<DateTime?>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<Guid>("RequestedForId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_for_id");

                    b.Property<Guid>("RequestedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_from_id");

                    b.HasKey("Id")
                        .HasName("pk_certificate_requests");

                    b.HasIndex("RequestedForId")
                        .HasDatabaseName("ix_certificate_requests_requested_for_id");

                    b.HasIndex("RequestedFromId")
                        .HasDatabaseName("ix_certificate_requests_requested_from_id");

                    b.ToTable("certificate_requests", "unified");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Certificates.Certificate", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<bool>("CanSign")
                        .HasColumnType("boolean")
                        .HasColumnName("can_sign");

                    b.Property<string>("EncodedValue")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("encoded_value");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issued_by");

                    b.Property<string>("IssuedTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issued_to");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<int>("PathLen")
                        .HasColumnType("integer")
                        .HasColumnName("path_len");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text")
                        .HasColumnName("private_key");

                    b.Property<Guid>("SignedById")
                        .HasColumnType("uuid")
                        .HasColumnName("signed_by_id");

                    b.Property<string>("SigningCertificateSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("signing_certificate_serial_number");

                    b.HasKey("SerialNumber")
                        .HasName("pk_certificates");

                    b.HasIndex("SignedById")
                        .HasDatabaseName("ix_certificates_signed_by_id");

                    b.HasIndex("SigningCertificateSerialNumber")
                        .HasDatabaseName("ix_certificates_signing_certificate_serial_number");

                    b.ToTable("certificates", "unified");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<string>("ReplacedByHashHex")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_hash_hex");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHashHex")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash_hex");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHashHex")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash_hex");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "unified");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hashed_password");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("organization");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "unified");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Users.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHashHex")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash_hex");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verification_tokens");

                    b.HasIndex("TokenHashHex")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_tokens_token_hash_hex");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_verification_tokens_user_id");

                    b.ToTable("verification_tokens", "unified");
                });

            modelBuilder.Entity("CertificateUser", b =>
                {
                    b.HasOne("SudoBox.UnifiedModule.Domain.Certificates.Certificate", null)
                        .WithMany()
                        .HasForeignKey("MyCertificatesSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificate_user_certificates_my_certificates_serial_number");

                    b.HasOne("SudoBox.UnifiedModule.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificate_user_users_user_id");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.CertificateRequests.CertificateRequest", b =>
                {
                    b.HasOne("SudoBox.UnifiedModule.Domain.Users.User", "RequestedFor")
                        .WithMany()
                        .HasForeignKey("RequestedForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificate_requests_users_requested_for_id");

                    b.HasOne("SudoBox.UnifiedModule.Domain.Users.User", "RequestedFrom")
                        .WithMany()
                        .HasForeignKey("RequestedFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificate_requests_users_requested_from_id");

                    b.Navigation("RequestedFor");

                    b.Navigation("RequestedFrom");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Certificates.Certificate", b =>
                {
                    b.HasOne("SudoBox.UnifiedModule.Domain.Users.User", "SignedBy")
                        .WithMany()
                        .HasForeignKey("SignedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificates_users_signed_by_id");

                    b.HasOne("SudoBox.UnifiedModule.Domain.Certificates.Certificate", "SigningCertificate")
                        .WithMany()
                        .HasForeignKey("SigningCertificateSerialNumber")
                        .HasConstraintName("fk_certificates_certificates_signing_certificate_serial_number");

                    b.Navigation("SignedBy");

                    b.Navigation("SigningCertificate");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("SudoBox.UnifiedModule.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("SudoBox.UnifiedModule.Domain.Users.VerificationToken", b =>
                {
                    b.HasOne("SudoBox.UnifiedModule.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_tokens_users_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
